config/routes.rb
Epione::Application.routes.draw do

	resources :quick_diagnoses, only: [:new, :create, :update]
	get '/quick_diagnoses/:id/correct', to: 'quick_diagnoses#correct', as: 'correct_quick_diagnosis'

	resources :quick_test_faqs, only: [:new, :create]
	resources :quick_test_minimentals, only: [:new, :create]

  resource :support, only: [:new]

	resource :contact_forms, only: [:create]

  resources :fototests, only: [:new, :create]
  get 'fototests/help', to: 'fototests#help', as: 'help_fototest'

  # the following solution was found in http://stackoverflow.com/questions/3791096/devise-logged-in-root-route-rails-3
  authenticated :physician do
    root :to => "quick_diagnoses#new"
  end
  unauthenticated :physician do
    devise_scope :physician do
      get "/" => "home#index"
      get "inicio" => "devise/sessions#new"
    end
  end
  get 'info' => 'home#info'
  get 'privacidad' => 'home#privacy'



  devise_for :physicians, :skip => [:registrations] # this lines and the below disable registration and allow only edit profile refer: http://stackoverflow.com/questions/6734323/how-do-i-remove-the-devise-route-to-sign-up
	as :physician do
		get 'physicians/edit' => 'devise/registrations#edit', :as => 'edit_physician_registration'
		put 'physicians' => 'devise/registrations#update', :as => 'physician_registration'
	end

  devise_for :admins  # This line has to be above mount RailsAdmin::Engine , if not , it makes an endless loop.

  mount RailsAdmin::Engine => '/administrator', :as => 'rails_admin'



end

app/models/physician.rb
class Physician < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable

  validates :name, :surname, presence: true

	has_many :computer_diagnoses, dependent: :nullify
  has_many :fototests, dependent: :nullify

  def full_name
    self[:name] + ' ' + self[:surname]
  end
end

app/views/physicians/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to '', new_session_path(resource_name), class:'icon-double-angle-left icon-2x'  %><br />
<% end -%>


<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "¿Olvidaste tu contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>