config/routes.rb
Epione::Application.routes.draw do

	resources :quick_diagnoses, only: [:new, :create, :update]
	get '/quick_diagnoses/:id/correct', to: 'quick_diagnoses#correct', as: 'correct_quick_diagnosis'

	resources :quick_test_faqs, only: [:new, :create]
	resources :quick_test_minimentals, only: [:new, :create]

  resource :support, only: [:new]

	resource :contact_forms, only: [:create]

  resources :fototests, only: [:new, :create]
  get 'fototests/help', to: 'fototests#help', as: 'help_fototest'

  # the following solution was found in http://stackoverflow.com/questions/3791096/devise-logged-in-root-route-rails-3
  authenticated :physician do
    root :to => "quick_diagnoses#new"
  end
  unauthenticated :physician do
    devise_scope :physician do
      get "/" => "home#index"
      get "inicio" => "devise/sessions#new"
    end
  end
  get 'info' => 'home#info'
  get 'privacidad' => 'home#privacy'



  devise_for :physicians, :skip => [:registrations] # this lines and the below disable registration and allow only edit profile refer: http://stackoverflow.com/questions/6734323/how-do-i-remove-the-devise-route-to-sign-up
	as :physician do
		get 'physicians/edit' => 'devise/registrations#edit', :as => 'edit_physician_registration'
		put 'physicians' => 'devise/registrations#update', :as => 'physician_registration'
	end

  devise_for :admins  # This line has to be above mount RailsAdmin::Engine , if not , it makes an endless loop.

  mount RailsAdmin::Engine => '/administrator', :as => 'rails_admin'



end

app/views/shared/_correct_diagnosis.html.erb
  <div class="row">
    <h3 class="text-muted">¿Esta de acuerdo con este diagnóstico?</h3>
  </div>
  <br>
  <div class="row">
		<div class="col-md-2 col-md-offset-3">
			<%= form_for @computer_diagnosis,
									 url: url do |f| %>
				<%= f.hidden_field :correct, value: 1 %>
				<%= f.submit 'Sí', class: 'btn btn-info btn-block' %>
			<% end %>
		</div>
    <div class="col-md-2">
			<%= form_for @computer_diagnosis,
									 url: url do |f| %>
				<%= f.hidden_field :correct, value: 0 %>
				<%= f.submit 'No', class: 'btn btn-default btn-block' %>
			<% end %>
    </div>
    <div class= "col-md-2" >
			<%= form_for @computer_diagnosis,
									 url: url do |f| %>
				<%= f.hidden_field :correct, value: 2 %>
				<%= f.submit 'Indeterminado', class: 'btn btn-default btn-grey btn-block' %>
			<% end %>
    </div>
  </div>

app/views/shared/_header.erb
<!--Page header and breadcrumb -->
<div class="page-header">
  <div class="row">

    <div class="col-md-8">
      <%= yield :top_left %>
      <%= breadcrumbs style: :bootstrap %>

      <% parent_breadcrumb do |link| %>
          <% if request.path !=  new_quick_diagnosis_path %>
          <div class="col-md-1">
          <%= link_to '', link.url , class:"icon-double-angle-left icon-2x" %>
        </div>
        <% end %>
      <% end %>

      <h1 class="featurette-heading">
        <%= yield :top_title %>
      </h1>

    </div>

    <div class="col-md-4">
      <%= yield :top_right %>
    </div>

  </div> <!--/row-->

</div> <!-- /Page-header-->

app/views/shared/_historico_habitos.erb
<!--Jumbotron containing a table -->
<div class="jumbotron">
  <div class="row">


    <h4>Histórico de Hábitos del paciente</h4>
    <div class="table-responsive">         <!--/.responsive-table-->
      <table class="table table-striped table-hover"  >
        <tr>

          <th>NHC</th>
          <th>Consulta</th>
          <th>Fecha</th>
          <th>Hábito</th>
          <th>Comentarios</th>
          <th>Detalles</th>
        </tr>

        <tbody id="habitos">
        <%= render partial: 'shared/habito', collection: habitos %>
        </tbody>
      </table>
    </div> <!--/.responsive-table-->

  </div><!-- /.row -->
</div> <!--/jumbotron-->

app/views/shared/_message.erb
<div class='<%= flash_class(style) %>'>
<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
<%= message %>
</div>

app/views/shared/_result_diagnosis.html.erb
<% message_kind = @computer_diagnosis.sane? ?  "alert-success" : "alert-danger" %>
<div class= "alert <%= message_kind %> alert-dismissable lead text-center" >
  <h3><%="#{@computer_diagnosis.diagnosis_text} - #{@computer_diagnosis.probability} %"%></h3>
</div>

app/views/shared/_tests_history_typed.erb
<!--Jumbotron containing a table -->
<div class="jumbotron">

  <h4>Test Realizados</h4>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
			<% if tests.any? %>
				<tr>
					<th>NHC</th>
					<th>Fecha de consulta</th>
					<th>Categoria de Test</th>
					<th>Test</th>
					<th>Score</th>
					<th>Detalles</th>
				</tr>


				<% tests.each do |test| %>
						<tr>
							<td><%= test.patient.id2 || t('no-nhc') %></td>       <!-- NHC -->
							<td><%= test.consultation.date %></td>       <!-- Fecha de Consulta -->
							<td><%= test.category_text %></td>       <!-- Categoría de Test -->
							<td><%= t(test.test_data_type) %></td>       <!-- Test -->
							<td><%= test.score%></td>       <!-- Score -->
							<td><%= link_to 'Ver detalles' , [test.consultation, test.test_data]%> </td>       <!-- Detalles -->

						</tr>
				<% end %>

			<% else %>
				<i>
                  No se le ha realizado ningun test a este paciente. Para realizar un test, seleccione una de las categorías arriba descritas.
				Dentro encontrará los tests de esa categoría.
                </i>
                  <!-- TODO - revisa este mensaje y formato -->
			<% end %>

    </table>
  </div> <!--/.responsive-table-->

</div> <!--/jumbotron-->

app/views/shared/_top_menu.erb
<!-- Static navbar -->
<div class="navbar-wrapper">
  <div class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to '.e-pione', root_path, class:'navbar-brand' %>

      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

          <li class=<%= 'active' if current_page?(new_fototest_path) %>>
            <%= link_to 'AP Screening', new_fototest_path %>
          </li>
          <li class=<%= 'active' if current_page?(new_quick_diagnosis_path) %>>
            <%= link_to 'SS Diagnose', new_quick_diagnosis_path %>
          </li>
          <li class=<%= 'active' if current_page?(new_support_path) %> >
            <%= link_to 'Contact', new_support_path %>
          </li>
          <li class=<%= 'active' if current_page?(edit_physician_registration_path) %> >
            <%= link_to 'Your account', edit_physician_registration_path %>
          </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li> <%= button_to 'Desconectarse', destroy_physician_session_path, :method => :delete, class: 'btn btn-default navbar-btn' %> </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>