config/routes.rb
Epione::Application.routes.draw do

	resources :quick_diagnoses, only: [:new, :create, :update]
	get '/quick_diagnoses/:id/correct', to: 'quick_diagnoses#correct', as: 'correct_quick_diagnosis'

	resources :quick_test_faqs, only: [:new, :create]
	resources :quick_test_minimentals, only: [:new, :create]

  resource :support, only: [:new]

	resource :contact_forms, only: [:create]

  resources :fototests, only: [:new, :create]
  get 'fototests/help', to: 'fototests#help', as: 'help_fototest'

  # the following solution was found in http://stackoverflow.com/questions/3791096/devise-logged-in-root-route-rails-3
  authenticated :physician do
    root :to => "quick_diagnoses#new"
  end
  unauthenticated :physician do
    devise_scope :physician do
      get "/" => "home#index"
      get "inicio" => "devise/sessions#new"
    end
  end
  get 'info' => 'home#info'
  get 'privacidad' => 'home#privacy'



  devise_for :physicians, :skip => [:registrations] # this lines and the below disable registration and allow only edit profile refer: http://stackoverflow.com/questions/6734323/how-do-i-remove-the-devise-route-to-sign-up
	as :physician do
		get 'physicians/edit' => 'devise/registrations#edit', :as => 'edit_physician_registration'
		put 'physicians' => 'devise/registrations#update', :as => 'physician_registration'
	end

  devise_for :admins  # This line has to be above mount RailsAdmin::Engine , if not , it makes an endless loop.

  mount RailsAdmin::Engine => '/administrator', :as => 'rails_admin'



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout "not_logged_in"
  def index
    @contact_form = ContactForm.new(params[:contact_form])
  end

  def testing
    render 'physicians/mailer/reset_password_instructions'
  end

  def quick_diagnosis

  end

  def info

  end

  def privacy

  end

end

app/views/home/about.html.erb
<div class="container">

  <div class="row front jumbotron jumbotron-home">


    <div class="col-md-8">
      <br><p></p>
      <%= image_tag 'logo_epione.png', class:'img-responsive img-rounded' %>
    </div>    <!--/col-md-8-->

    <div class="col-md-4">
      <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'form-signin'})   do |f| %>
          <h2 class="form-signin-heading text-muted-home">Por favor, identifíquese</h2>
          <div> <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'email' %></div>

          <div><%= f.password_field :password, class: 'form-control', placeholder: 'contraseña' %></div>

          <label class="checkbox checkbox-home">
            <%= f.check_box :remember_me %> <small>Recordarme</small>
          </label>

          <div><%= f.submit "Acceder", class: 'btn btn-lg btn-primary btn-block' %></div>

      <% end %>

      <small><%= link_to '¿Problemas para acceder?', support_path , class: 'text-muted-home' %> </small>  <!--- It was designed to get the small tag inside the a tag, it should be considered to be changed if it is necessary -->
      <br />
      <small><%= link_to '¿Olvido su contraseña?', new_physician_password_path , class: 'text-muted-home' %> </small>

    </div> <!--/col-md-4-->


  </div><!--/row-->

  <div class="row credits">
    <!--logos cremas aquí-->
    <div class="col-md-1 col-md-offset-2"><h4>Colaboran:</h4></div>
    <div class="col-md-3 col-md-offset-1">
      <h4> Dr. Juan Rafael García</h4>
      <h5>Jefe del servicio de neurología del Hospital Universitario Insular de G.C.</h5>
    </div>
    <div class="col-md-3">
      <a href="http://www.hospitalessanroque.com/">

      </a>
    </div>
    <!-- <div class="col-md-1 "><h4>Engineered by</h4></div>
    <div class="col-md-2">
      <a href="http://www.binnac.com/">
        <%= image_tag 'logobinnac.png', class:'img-responsive img-rounded' %>
      </a>
    </div>-->
  </div><!--/row-->
  <div class="page-scroll">
    <a href="#contact" class="btn btn-circle btn-no-border">
      <i class="fa fa-angle-double-down animated"></i>
    </a>
  </div>
</div> <!-- /container -->

app/views/home/index.html.erb
<section class="intro">
  <div class="intro-body">
    <div class="container container-top">
      <% if flash[:notice] %>
          <br>
          <div class="alert alert-success alert-dismissable col-md-6 col-md-offset-3 lead text-center">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= flash[:notice] %>
          </div>
      <%end%>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <!--Carousel -->

          <ul class="bxslider">
            <li><%= image_tag 'logo_epione_large.png', class:'img-rounded img-responsive ' %></li>
            <li><%= image_tag 'screen1.png', class:'img-responsive img-rounded' %></li>
            <li><%= image_tag 'screen5.png', class:'img-responsive img-rounded' %></li>

          </ul>
          <!--/Carousel -->
          <br>
          <div class="page-scroll">
            <%= link_to "Solicitar una prueba", '#colaborate' ,class: 'btn btn-lg btn-primary btn-try' %>
          </div>

        </div>  <!--/col -->
      </div><!--/row-->

      <div class="row subtitle">
        <div class="col-md-8 col-md-offset-2">
          <h3 class=""> Diagnóstico preciso con la puntuación del FAQ y del MMSE, la edad y la educación del paciente</h3>
          <div class="page-scroll">
            <a href="#about" class=""></a>
          </div>
          <div class="page-scroll">
            <a href="#about" class="btn btn-circle">
              <i class="icon-double-angle-down animated"></i>
            </a>
          </div>   <!--/page scroll -->
        </div>    <!--/col-->
      </div>   <!--/col-->
    </div><!-- /container -->
     </div><!-- /intro-body-->

</section>


<section id="about" class="container content-section about-section">
  <div class="row">
      <h2 class="text-center">E-PIONE: CRIBADO INTELIGENTE</h2>
  </div>
  <p></p>
  <div class = "row well-class text-left">
    <div class="col-lg-2 col-lg-offset-1"><a class="icon-zoom-in icon-4x"></a></div>
    <div class="col-lg-8">
      <h4>e-pione es un Sistema Inteligente de Ayuda al Diagnóstico (SIAD) del deterioro cognitivo (DC)
      </h4>
    </div>
  </div>


  <div class = "row well-class text-left">
    <div class="col-lg-2 col-lg-offset-1"><a class="icon-gears icon-4x"></a></div>
    <div class="col-lg-8">
      <h4>
        Construido a partir de las últimas técnicas de minería de  datos, aprendizaje automático y
        sistemas expertos, obtiene más de un 80 % de precisión totalmente balanceada
      </h4>
    </div>
  </div>
  <div class = "row well-class text-left">
    <div class="col-lg-2 col-lg-offset-1"><a class="icon-check icon-4x"></a></div>
    <div class="col-lg-8">
      <h4>
        Tan sólo es necesario el resultado del test FAQ, el MMSE, la edad y escolarización del paciente
      </h4>
    </div>
  </div>
  <div class = "row well-class text-left">
    <div class="col-lg-2 col-lg-offset-1"><a class="icon-group icon-4x"></a></div>
    <div class="col-lg-8">
      <h4>
        Los resultados han sido obtenidos y <%= link_to "validados", info_path %> sobre una base de datos de más de 1300 pacientes.
        Más información sobre la validación
        <%= link_to "aquí.", info_path %>

      </h4>
    </div>
  </div>
  <div class = "row well-class  text-left">
    <div class="col-lg-2 col-lg-offset-1"><a class="icon-time icon-4x"></a></div>
    <div class="col-lg-8">
      <h4>
        Tomar decisiones rápidamente no es suficiente cuando la salud está en juego.
        Por eso, la opinión de un comité de expertos (SIAD) de forma instantánea en tu consulta es
        un valor añadido en la calidad de tus diagnósticos
      </h4>
    </div>
  </div>
  <div class="row text-center">
    <div class="page-scroll">
      <a href="#colaborate" class="btn btn-circle">
        <i class="icon-double-angle-down animated"></i>
      </a>
    </div>
  </div>
</section>


<section id="colaborate" class="container content-section colaborate-section text-center">
  <div class="row">
    <h2>COLABORA CON NOSOTROS</h2>
  </div>
  <br>
  <p></p>
  <div class="row">

    <div class="col-md-5 col-md-offset-1">
      <p>Equipo consultivo</p>
      <dl class="text-left dl-horizontal">
        <dt>Dr. Cristóbal Carnero</dt>
        <dd>Jefe de Neurología Hospital de Granada</dd>
        <dd>Creador del Fototest y asesor del servicio</dd>
      </dl>
      <hr>
      <p>Colaboradores</p>
      <dl class="text-left dl-horizontal">
        <dt>Dr. Juan Rafael García </dt>
        <dd>Jefe Neurología del C.H.U. Insular-Materno Infantil</dd>


        <dt>Dra. María Pérez Vieitez </dt>
        <dd> Facultativo Especialista de Área Hospital Doctor Negrín, Unidad de Demencias</dd>
         <br>
        <dt>Dr. Domingo Quintana </dt>
        <dd><%= image_tag 'logoicot.png', class:'img-responsive img-rounded' %></dd>
        <br>
        <dt>Clínica San Roque</dt>
        <dd><%= image_tag 'logosanroque.png', class:'img-responsive img-rounded' %> </dd>

      </dl>
    </div>
        <%= render partial: 'contact_forms/form', locals: { contact_form: ContactForm.new } %>
  </div> <!--/row-->
  <div class="row text-center">
    <div class="page-scroll go-up-scroll">
      <a href="#page-top" class="">
        <i class="icon-double-angle-up icon-3x animated"></i>
      </a>
    </div>
  </div>

</section>

app/views/home/info.html.erb
<br>
<br>
<br>
<!--TODO: Si le damos atrás aquí hay problemas con el carousel la página principal tendrá
 que ver con jquery y document ready fijo-->
<div class="container">


  <h2 class="text-center">E-PIONE: VALIDACIÓN DEL SISTEMA </h2>

  <h4><p>e-pione es un Sistema Inteligente de Ayuda al Diagnóstico (SIAD) del Deterioro Cognitivo (DC)
que presenta más de un 80% de precisión balanceada entre clases, calculada como la media de la sensibilidad y la especificidad.
</p></h4>
<h4><p>Para la construcción del SIAD se han empleado técnicas de minería de datos aplicadas a un
conjunto de más de 1300 pacientes. La fase de aprendizaje se ha llevado a cabo sobre 514 pacientes
  (257 sanos y 257 con DC), seleccionando el punto óptimo de la curva ROC en base a un conjunto que
  denominamos de validación compuesto de 103 sanos y 103 con DC. El valor final, el 80% comentado anteriormente,
  es el valor de validación cruzada obtenido utilizando un conjunto de test de 657 pacientes (503 con DC y 154 sanos) que el SIAD no ha visto previamente, algo imprescindible para garantizar su capacidad de generalización.
</p></h4>

<h4><p>En la siguiente tabla se muestra información sobre los atributos
de los sujetos de la muestra, separados por diagnóstico: envejecimiento normal o DC.
Los valores se presentan como la media ± la desviación estándar, y entre paréntesis se indica el rango (valor mínimo-valor máximo).
</p>
</h4>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-striped table-bordered">
        <thead>
            <th></th>
            <th>Sanos</th>
            <th>DC</th>
            <th>Sanos + DC</th>
        </thead>

        <tbody>
            <tr>
              <td>Cantidad</td>
              <td>514</td>
              <td>863</td>
              <td>1377</td>
            </tr>
            <tr>
              <td>Edad</td>
              <td>74.44±5.76(56.25−90.16)</td>
              <td>73.13±7.62(48.15−91.45)</td>
              <td>73.62 ± 7.01(48.15-91.45)</td>
            </tr>
            <tr>
              <td>Educación</td>
              <td>16.36±2.71(6−20)</td>
              <td>15.92±2.84(4−20)</td>
              <td>16.09 ± 2.80(4-20)</td>
            </tr>
            <tr>
              <td>FAQ</td>
              <td>0.23±0.95(0−13)</td>
              <td>3.19±4.11(0-22</td>
              <td>2.09 ± 3.60(0-22)</td>
            </tr>
            <tr>
              <td>MMSE</td>
              <td>29.05±1.14(24−30)</td>
              <td>27.57±1.82(23−30)</td>
              <td>28.13 ± 1.75(23-30)</td>
            </tr>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/home/privacy.html.erb
<div class="container">
  <h2 class="text-center"> TÉRMINOS DE PRIVACIDAD</h2>

  <p>

  BINNAC, por medio de su representante, David Díaz Clavijo,y  en adelante Clavijo, tiene como uno de sus principales objetivos ofrecer un servicio lo más seguro y confidencial posible, asegurando la privacidad de las comunicaciones y los datos personales de sus usuarios.

  Si el usuario desea tener acceso a los servicios ofrecidos en el sitio web de E-PIONE debe prestar su consentimiento de forma patente y voluntaria, cumplimentando los formularios de solicitud de registro.

  Clavijo está comprometido con Internet y con sus usuarios.</p>
   <p>
   Por ello, tiene como uno de sus principales compromisos cumplir y hacer cumplir los hábitos y normas de etiqueta de Internet y la legislación vigente en cada momento.

  La base de datos generada a partir del sitio E-PIONE es propiedad de Clavijo. En su calidad de propietario, el responsable de este fichero es Clavijo.
  </p>
 <p>
  Clavijo garantiza el cumplimiento de la normativa en materia de protección de datos,
  bajo los términos estipulados en la Ley Orgánica 15/1999, de 13 de diciembre,
  de Protección de Datos de Carácter Personal (en adelante, LOPD).
 </p>
  <p>
  Clavijo dispone de las medidas de seguridad para que
  de la mejor manera posible se garantice la seguridad y confidencialidad en el tratamiento automatizado de los datos de carácter personal sujetos a la LOPD.
  De acuerdo a lo establecido en el artículo 12 de la LOPD, Clavijo
  sólo accederá a los datos personales que el usuario ha almacenado en la base de datos conforme a sus instrucciones explícitas, y no los aplicará o utilizará con fin distinto al que figure en dicho contrato, ni los comunicará, ni siquiera para su conservación, a otras personas.
</p>
  <p>
  Los datos referentes a la solicitud de un diagnóstico de cualquier enfermedad neurodegenerativa y la opinión del usuario sobre su validez serán usados para mejorar el servicio inteligente de ayuda al diagnóstico. En ningún caso los datos de solicitud de un diagnóstico permiten conocer los datos personales del paciente para el que fue solicitado.

  En el momento en que un usuario solicita su registro en el servidor de E-PIONE sus datos personales pueden ser incorporados a la base de datos de E-PIONE para ofrecerle los productos y disfrutar de los servicios de E-PIONE.
   </p>
   <p>
  De conformidad con lo dispuesto en la normativa vigente, se comunica a los usuarios que cumplimenten
  el formulario correspondiente que sus datos personales serán incorporados a un fichero cuya creación ha
   sido debidamente notificada ante la Agencia Española de Protección de Datos.
  </p>
  <p>
  En todo momento, el usuario podrá ejercitar sus derechos de acceso, rectificación, cancelación y
    oposición al tratamiento de datos personales mediante comunicación remitida al Centro de Atención
    al Cliente de E-PIONE enviando un mensaje por correo electrónico a la dirección electrónica: soporte@e-pione.com.
</p>
  <h4>COOKIES</h4>
  <p>
  Una cookie es un fichero que se descarga en tu dispositivo al acceder a determinadas páginas Web.
  Las cookies permiten a la página Web, entre otras cosas, almacenar y recuperar información sobre tu
  número de visitas, los hábitos de navegación del usuario o de su equipo y, dependiendo de la información
  que contengan y de la forma en que utilice su equipo,
  pueden utilizarse para reconocer al usuario.
</p>
  <p>
  En las páginas web de E-PIONE utilizamos los siguientes tipos de cookies, las cuales son tratadas bien
  por nosotros directamente o por terceros colaboradores:
  </p>

  <p>
  Cookies técnicas:
    Son aquellas utilizadas por E-PIONE que permiten al usuario
  la navegación a través de la página Web y la utilización de las diferentes opciones o servicios
  que en ella existen como, por ejemplo, recordar los tests realizados y recordar la última sesión iniciada.
  </p>
  <p>
  Cookies de análisis: Son aquellas utilizadas por E-PIONE y por
    <%=link_to 'Google Analytics','http://www.google.com/intl/es/policies/privacy/',
               class: 'blue-link'%>  que nos permiten cuantificar el número de usuarios y así realizar la medición y análisis
    estadístico de la utilización y actividad que hacen los usuarios de nuestra página Web, así como elaborar de perfiles de navegación de los usuarios en dichas páginas y en nuestras aplicaciones, todo ello con el fin de introducir mejoras.
  </p>
  <p>
  Ten en cuenta que para poder utilizar determinados servicios y funcionalidades que
  te ofrecemos en E-PIONE es necesario que tengas habilitadas las cookies en tu navegador de Internet.
  </p>
  <p>
  En concreto, mediante estas cookies técnicas, E-PIONE podrá identificarte como usuario
  registrado cada vez que accedas a nuestra plataforma, permitiéndote así el acceso y uso a dichos servicios
    y funcionalidades.
  </p>
  <p>
  No obstante, recuerda que puedes permitir, bloquear o eliminar estas cookies cuando quieras a través de las opciones de configuración de tu navegador:
  </p>
  <p>
  <ul>
      <li><%=link_to 'Safari','http://support.apple.com/kb/HT1677?viewlocale=es_ES&locale=es_ES',
                     class: 'blue-link'%></li>
      <li><%= link_to 'Google Chrome', 'https://support.google.com/chrome/answer/95647?hl=es' ,
                      class: 'blue-link' %></li>
      <li><%= link_to 'Mozilla Firefox',
                      ' https://support.mozilla.org/es/kb/cookies-informacion-que-los-sitios-web-guardan-en-' ,
                      class: 'blue-link' %></li>
      <li><%= link_to 'Internet Explorer',
                      'http://windows.microsoft.com/es-xl/internet-explorer/delete-manage-cookies#ie=ie-10' ,
                      class: 'blue-link' %></li>
  </ul>
  </p>
  <p>
  Recuerda siempre acceder a la información de soporte más actualizada de dichos navegadores
    para conocer el modo en que puedes eliminar las cookies, dado que el modo puede diferir
    entre distintas versiones y sistemas operativos.
 </p>
 <p>
  En el caso de que utilices cualquier otro navegador de Internet,
   te recomendamos que consultes sus opciones de gestión de cookies.
 </p>



  </div>

app/views/home/support.html.erb
<div class="container">
  <h2 class="text-center">¿Problemas para acceder?</h2>
  <h3 class="text-center">Contáctenos en la siguiente dirección o teléfono  y le atenderemos rápidamente</h3>
  <hr>



  <a href="mailto: soporte@e-pione.com"><h3 class="text-center text-primary"> soporte@e-pione.com</h3></a>
  <%=  link_to "", root_path, class:"icon-double-angle-left icon-2x" %>

</div>

app/views/home/support.html.haml
.container
  %h2.text-center Contáctanos
  %h3.text-center Contáctenos en la siguiente dirección y le atenderemos rápidamente
  %hr/
  %a{href: "mailto: soporte@e-pione.com"}
    %h3.text-center.text-primary soporte@e-pione.com