config/routes.rb
Epione::Application.routes.draw do

	resources :quick_diagnoses, only: [:new, :create, :update]
	get '/quick_diagnoses/:id/correct', to: 'quick_diagnoses#correct', as: 'correct_quick_diagnosis'

	resources :quick_test_faqs, only: [:new, :create]
	resources :quick_test_minimentals, only: [:new, :create]

  resource :support, only: [:new]

	resource :contact_forms, only: [:create]

  resources :fototests, only: [:new, :create]
  get 'fototests/help', to: 'fototests#help', as: 'help_fototest'

  # the following solution was found in http://stackoverflow.com/questions/3791096/devise-logged-in-root-route-rails-3
  authenticated :physician do
    root :to => "quick_diagnoses#new"
  end
  unauthenticated :physician do
    devise_scope :physician do
      get "/" => "home#index"
      get "inicio" => "devise/sessions#new"
    end
  end
  get 'info' => 'home#info'
  get 'privacidad' => 'home#privacy'



  devise_for :physicians, :skip => [:registrations] # this lines and the below disable registration and allow only edit profile refer: http://stackoverflow.com/questions/6734323/how-do-i-remove-the-devise-route-to-sign-up
	as :physician do
		get 'physicians/edit' => 'devise/registrations#edit', :as => 'edit_physician_registration'
		put 'physicians' => 'devise/registrations#update', :as => 'physician_registration'
	end

  devise_for :admins  # This line has to be above mount RailsAdmin::Engine , if not , it makes an endless loop.

  mount RailsAdmin::Engine => '/administrator', :as => 'rails_admin'



end

app/models/fototest.rb
class Fototest < ActiveRecord::Base
  attr_accessor :siad_params_validation
  belongs_to :physician
  validates :physician_id, presence: true
  validates :age, :education, presence: true
  validates :cartas1, :coche1, :pera1, :trompeta1, :zapatos1, :cuchara1, :cartas2, :coche2, :pera2, :trompeta2, :zapatos2, :cuchara2, :cartas3, :coche3, :pera3, :trompeta3, :zapatos3, :cuchara3, presence: true
  validates :total_hombres, :total_mujeres, presence: true
  validates :gender, presence: true
  validates :education, inclusion: { in: 0..20 }
  validates :probability, :diagnosis, presence: true, unless: 'siad_params_validation'

  def deno
    cartas1 + coche1 + pera1 + trompeta1 + zapatos1 + cuchara1
  end

  def rl
    cartas2 + coche2 + pera2 + trompeta2 + zapatos2 + cuchara2
  end

  def rf
    cartas3 + coche3 + pera3 + trompeta3 + zapatos3 + cuchara3
  end

  def memoria
    rl + rf
  end

  def fluidez
    total_hombres + total_mujeres
  end

  def total
    deno + rl + rf + total_hombres + total_mujeres
  end

  # Code duplicated, consider refactoring
  def valid_siad_exec?
    self.siad_params_validation = true
    aux = valid?
    self.siad_params_validation = nil
    aux
  end

  def diagnosis_text
    INT_TO_DIAGNOSIS[self.diagnosis]
  end

  def sane?
    diagnosis == 0
  end

  def mci?
    diagnosis == 1
  end

  private

  INT_TO_DIAGNOSIS = {
      0 => 'Sane',
      1 => 'Cognitive Impairment'
  }
end

app/controllers/fototests_controller.rb
class FototestsController < ApplicationControllerSigned

  def new
    @fototest = Fototest.new
  end

  def create
    @fototest = current_physician.fototests.new fototest_params
    if @fototest.valid_siad_exec?
      siad_params = fototest_params.to_hash.symbolize_keys
      siad_params.delete :education_select
      @fototest.diagnosis, @fototest.probability = fototest_siad edad: @fototest.age,
                                                                 sexo: @fototest.gender ,
                                                                 rl: @fototest.rl, rf: @fototest.rf, memoria: @fototest.memoria,
                                                                 hombres: @fototest.total_hombres, mujeres: @fototest.total_mujeres,
                                                                 fluidez: @fototest.fluidez, fototest: @fototest.total,
                                                                 estudio: @fototest.education
      siad_error = true unless ( @fototest.diagnosis && @fototest.probability )
    end
    respond_to do |format|
      if siad_error
        flash[:alert]= 'Ha habido un error. Por favor contacte a los administradores. '
        format.html { redirect_to new_fototest_path }
      else
        if @fototest.save
          format.html { render 'show'	}
        else
          #FIXME: Cuando hay un error, se rellenan los campos y se envia el test, el
          #flash aparece en show y no debería.
          flash[:error]= 'Por favor introduzca, edad, sexo y nivel de estudios '
          format.html { render action: 'new' }
        end
      end
    end
  end

  def help

  end

  private
    def fototest_siad (
        edad: nil, sexo: nil,
        rl: nil, rf: nil, memoria: nil, hombres: nil, mujeres: nil, fluidez: nil,
        fototest: nil,
        estudio: nil
    )

      python_script = 'python3.3  /opt/fototest/fototest.py'
      return nil unless edad && sexo && # all the args are mandatory
          rl && rf && memoria && hombres && mujeres && fluidez &&
          fototest && estudio
      # python3.4 SIAD/fototest.py SEXO:0 EDAD:50 RL:8 RF:2 MEMORIA:10 HOMBRES:8 MUJERES:8 FLUIDEZ:16 FOTOTEST:25 ESTUDIO:10
      result = `#{python_script} SEXO:#{sexo} EDAD:#{edad} RL:#{rl} RF:#{rf} MEMORIA:#{memoria} HOMBRES:#{hombres} MUJERES:#{mujeres} FLUIDEZ:#{fluidez} FOTOTEST:#{fototest} ESTUDIO:#{estudio} `
      output_reg = /(\d)\s+(\d+\.\d+)/
      if output_reg.match result
        diagnosis = $1.to_i
        probability = $2.to_f
        [ diagnosis, probability ]
      else
        nil
      end
    end

    def fototest_params
      params.require(:fototest).permit(:age, :education, :gender,
                                       :cartas1, :coche1, :pera1, :trompeta1,
                                       :zapatos1, :cuchara1, :cartas2, :coche2,
                                       :pera2, :trompeta2, :zapatos2, :cuchara2,
                                       :cartas3, :coche3, :pera3, :trompeta3,
                                       :zapatos3, :cuchara3, :total_hombres,
                                       :total_mujeres)
    end

end

app/views/fototests/create.html.haml
.ContLAncho
  .OCntL
    .NoSubSp
      %p
        %span.Neg> Nombre:
        _________________________________________________
      %p
        %span.Neg> Número de Historia:
        _______
      %p
        %span.Neg
          Edad:
          %span.rojo= @edad
          Fecha:
          %span.rojo= @fecha
    %table{border: '1', summary: 'Formulario del Fototest: resultados obtenidos', width: '90%'}
      %caption.FatH2 Fototest - Test de las Fotos
      %tr.FatH3
        %td.Neg{width: '15ex'} Categoría
        %td.Neg{width: '10ex'} Fotos
        %td.Neg.centrar{width: '7ex'} Den
        %td.Neg.centrar{width: '7ex'} RL
        %td.Neg.centrar{width: '7ex'} RF
        %td.Neg.centrar{width: '50ex'} Fluidez hombres (FH)
        %td.Neg.centrar{width: '50ex'} Fluidez mujeres (FM)
      %tr
        %td.Neg Juego
        %td.Neg Cartas
        %td.centrar= @fototest.cartas1
        %td.centrar= @fototest.cartas2
        %td.centrar= @fototest.cartas3
        %td.centrar{rowspan: '6'}  
        %td.centrar{rowspan: '6'}  
      %tr
        %td.Neg Vehículo
        %td.Neg Coche
        %td.centrar= @fototest.coche1
        %td.centrar= @fototest.coche2
        %td.centrar= @fototest.coche3
      %tr
        %td.Neg Fruta
        %td.Neg Pera
        %td.centrar= @fototest.pera1
        %td.centrar= @fototest.pera2
        %td.centrar= @fototest.pera3
      %tr
        %td.Neg Inst. Musical
        %td.Neg Trompeta
        %td.centrar= @fototest.trompeta1
        %td.centrar= @fototest.trompeta2
        %td.centrar= @fototest.trompeta3
      %tr
        %td.Neg Prenda vestir
        %td.Neg Zapatos
        %td.centrar= @fototest.zapatos1
        %td.centrar= @fototest.zapatos2
        %td.centrar= @fototest.zapatos3
      %tr
        %td.Neg Cubierto
        %td.Neg Cuchara
        %td.centrar= @fototest.cuchara1
        %td.centrar= @fototest.cuchara2
        %td.centrar= @fototest.cuchara3
      %tr
        %td.Neg{colspan: '2'} Subtotales
        %td.centrar= @fototest.total1
        %td.centrar= @fototest.total2
        %td.centrar= @fototest.total3
        %td.centrar= @fototest.totalHombres
        %td.centrar= @fototest.totalMujeres
      %tr
        %td.Neg{colspan: '6'} Total Test de las Fotos (Den + RL + RF + FH + FM)
        %td.centrar= @fototest.total
    %p
      %span.Neg
        Este resultado corresponde a un percentil
        %span.rojo 5
        y a una puntuación Z de
        = succeed '.' do
          %span.rojo -4,05
    %p
      %span.Neg
        Una puntuación como esta o inferior tiene un cociente de probabilidad positivo de
        %span.rojo
          %span.FatH2 ∞
        para demencia y
        %span.rojo
          %span.FatH2 ∞
        para deterioro cognitivo, y un cociente de probabilidad negativo de
        %span.rojo 0.78
        para demencia y
        %span.rojo 0.87
        para deterioro cognitivo.
    .centrar
      %input{onclick: "parent.location='#{new_fototests_path}'", type: 'button', value: 'Nuevo test'}/
      %input{onclick: 'window.print()', type: 'button', value: 'Imprimir'}/

app/views/fototests/new.html.haml
- content_for :title do
  AP screening
- content_for :top_title do
  AP: screening
%p.lamina
  = image_tag 'fototest.jpg', alt: 'Lámina del Fototest', size: '900x638', usemap: '#Map2',
  class:'img-responsive center-block'
  %map#Map2
    %area{alt: 'cartas', coords: '75,141,278,266', href: 'javascript:void(0)', onclick: "SumaAciertoCartas('denom');", shape: 'rect'}/
    %area{alt: 'coche', coords: '310,120,629,291', href: 'javascript:void(0)', onclick: "SumaAciertoCoche('denom');", shape: 'rect'}/
    %area{alt: 'pera', coords: '689,108,810,301', href: 'javascript:void(0)', onclick: "SumaAciertoPera('denom');", shape: 'rect'}/
    %area{alt: 'trompeta', coords: '71,373,316,452', href: 'javascript:void(0)', onclick: "SumaAciertoTrompeta('denom');", shape: 'rect'}/
    %area{alt: 'zapatos', coords: '352,331,542,506', href: 'javascript:void(0)', onclick: "SumaAciertoZapatos('denom');", shape: 'rect'}/
    %area{alt: 'cuchara', coords: '600,384,819,444', href: 'javascript:void(0)', onclick: "SumaAciertoCuchara('denom');", shape: 'rect'}/
%p
  .row
    .col-md-4.col-md-offset-2
      %button#toggle.btn.btn-primary.btn-block Press to hide/show sheet
    .col-md-3.col-md-offset-1
      %input#ayuda.btn.btn-default.btn-block{name: 'ayuda',type: 'button',
             onclick:"parent.location='#{help_fototest_path}'",value: 'Help / Instructions'}/
= form_for @fototest, html: {id: 'form1'}, url: fototests_path do |f|
  .table-responsive.text-center
    %table.table.table-condensed.table-bordered{border: '0 ', summary: 'Formulario del test de las fotos. En él se introducen automá…ltados de las distintas fases de la administración del test.', width: '90%'}
      %caption Phototest - Test of the photos
      %thead
        %tr.active
          %th
            %span Category
          %th Photos
          %th.text-center Denomination
          %th.text-center Free recall
          %th.text-center Aided recall
          %th.text-center
            %label{for: 'iniciaHombres', style: @fototest.errors[:total_hombres_set].any? ? 'border: 5px groove #ff0000;' : '' }
            %input#iniciaHombres{name: 'radio', onclick: 'temporizador = 0;clearTimeout(countdown);', type: 'radio', value: 'hombres'}/
            Verbal fluency men
          %th.text-center
            %label{for: 'iniciaMujeres', style: @fototest.errors[:total_mujeres_set].any? ? 'border: 5px groove #ff0000;' : '' }
            %input#iniciaMujeres{name: 'radio', onclick: 'temporizador = 0;clearTimeout(countdown);', type: 'radio', value: 'mujeres'}/
            Verbal fluency women
      %tfoot
        %tr
          %td.h4.text-right{colspan: '6'} Phototest total(Den + FR + AR + VFM + VFW)
          %td.h4#Resultado 0
      %tbody
        %tr
          %td.text-left Game
          %td.text-left Cards
          %td
            %input#carta1{name: 'carta1', onclick: "SumaAciertoCartas('denom');", type: 'button', value: '±',  class:'btn btn-default'}/
            %span#ca1 0
          %td
            %input#carta2{name: 'carta2', onclick: "SumaAciertoCartas('libre');", type: 'button', value: '±',  class:'btn btn-default'}/
            %span#ca2 0
          %td
            %input#carta3{name: 'carta3', onclick: "SumaAciertoCartas('facil');", type: 'button', value: '±',  class:'btn btn-default'}/
            %span#ca3 0
          %td{rowspan: '5'}
            %input#hombresInc{name: 'hombresInc', onclick: 'sonHombres = 1;sonMujeres = 0;countdown_init();incHombres();', type: 'button', value: '+', class:'btn btn-default'}/
            %input#hombresDec{name: 'hombresDec', onclick: 'sonHombres = 1;sonMujeres = 0;decHombres()', type: 'button', value: '-', class:'btn btn-default'}/
          %td{rowspan: '5'}
            %input#mujeresInc{name: 'mujeresInc', onclick: 'sonMujeres = 1;sonHombres = 0;countdown_init();incMujeres();', type: 'button', value: '+', class:'btn btn-default'}/
            %input#mujeresDec{name: 'mujeresDec', onclick: 'sonMujeres = 1;sonHombres = 0;decMujeres()', type: 'button', value: '-', class:'btn btn-default'}/
        %tr
          %td.text-left Vehicle
          %td.text-left Car
          %td
            %input#coch1{name: 'coch1', onclick: "SumaAciertoCoche('denom');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#co1 0
          %td
            %input#coch2{name: 'coch2', onclick: "SumaAciertoCoche('libre');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#co2 0
          %td
            %input#coch3{name: 'coch3', onclick: "SumaAciertoCoche('facil');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#co3 0
        %tr
          %td.text-left Fruit
          %td.text-left Pear
          %td
            %input#per1{name: 'per1', onclick: "SumaAciertoPera('denom');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#pe1 0
          %td
            %input#per2{name: 'per2', onclick: "SumaAciertoPera('libre');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#pe2 0
          %td
            %input#per3{name: 'per3', onclick: "SumaAciertoPera('facil');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#pe3 0
        %tr
          %td.text-left Musical inst.
          %td.text-left Trumpet
          %td
            %input#trompet1{name: 'trompet1', onclick: "SumaAciertoTrompeta('denom');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#tr1 0
          %td
            %input#trompet2{name: 'trompet2', onclick: "SumaAciertoTrompeta('libre');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#tr2 0
          %td
            %input#trompet3{name: 'trompet3', onclick: "SumaAciertoTrompeta('facil');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#tr3 0
        %tr
          %td.text-left Piece of clothing
          %td.text-left Shoes
          %td
            %input#zapato1{name: 'zapato1', onclick: "SumaAciertoZapatos('denom');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#za1 0
          %td
            %input#zapato2{name: 'zapato2', onclick: "SumaAciertoZapatos('libre');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#za2 0
          %td
            %input#zapato3{name: 'zapato3', onclick: "SumaAciertoZapatos('facil');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#za3 0
        %tr
          %td.text-left Cutlery
          %td.text-left Spoon
          %td
            %input#cuchar1{name: 'cuchar1', onclick: "SumaAciertoCuchara('denom');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#cu1 0
          %td
            %input#cuchar2{name: 'cuchar2', onclick: "SumaAciertoCuchara('libre');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#cu2 0
          %td
            %input#cuchar3{name: 'cuchar3', onclick: "SumaAciertoCuchara('facil');", type: 'button', value: '±', class:'btn btn-default'}/
            %span#cu3 0
          %td.text-center{colspan: '2'}
            %span.h4 Remaining time:
            %span#countdown_text.h4 30
            %span.h4 s
        %tr
          %td{colspan: '2'} Subtotals:
          %td#totalDenom 0
          %td#totalLibre 0
          %td#totalFacil 0
          %td#totalHombres 0
          %td#totalMujeres 0
    .row.text-left
      .col-md-2
        %label{for: 'Age'}
          Age:
          %p
          = f.number_field :age , class:'form-control'
      .col-md-2
        //FIXME: Radio button se desplazan cuando hay un error y no se colorean de rojo
        = f.label :education, 'Gender'
        %p
        %label.radio
          Man
          = f.radio_button :gender ,'0'
        %label.radio
          Woman
          = f.radio_button :gender ,'1'

      .col-md-7
        #education
          = f.label :education, 'Education Level'
          %p
          %label.radio
            Below Primary Studies
            = f.radio_button :education ,'0'
          %label.radio
            Primary Studies
            = f.radio_button :education ,'1'
          %label.radio
            Above Primary Studies
            = f.radio_button :education ,'2'
        %br/
    = f.hidden_field :cartas1
    = f.hidden_field :cartas2
    = f.hidden_field :cartas3
    = f.hidden_field :coche1
    = f.hidden_field :coche2
    = f.hidden_field :coche3
    = f.hidden_field :pera1
    = f.hidden_field :pera2
    = f.hidden_field :pera3
    = f.hidden_field :trompeta1
    = f.hidden_field :trompeta2
    = f.hidden_field :trompeta3
    = f.hidden_field :zapatos1
    = f.hidden_field :zapatos2
    = f.hidden_field :zapatos3
    = f.hidden_field :cuchara1
    = f.hidden_field :cuchara2
    = f.hidden_field :cuchara3
    = f.hidden_field :total_hombres
    = f.hidden_field :total_mujeres
    .row
      .col-md-3.col-md-offset-2
        %input.btn.btn-primary.btn-block#Enviar{name: 'Enviar', onclick: 'send_form();', type: 'submit', value: 'Send data'}/
      .col-md-3.col-md-offset-1
        %input.btn.btn-default.btn-block#Reset{name: 'Reset', onclick: "cartas1 = coche1 = pera1 = trompeta1 = zapatos1 = cuchara1 = cartas2 = coche2 = pera2 = trompeta2 = zapatos2 = cuchara2 = cartas3 = coche3 = pera3 = trompeta3 = zapatos3 = cuchara3 = totalDenom = totalLibre = totalFacil = totalHombres = totalMujeres = puntos = temporizador = countdown_number = sonHombres = sonMujeres = 0; fase = 'ninguna'; clearTimeout(countdown);", type: 'reset', value: 'New test'}/
    %br
    %br

app/views/fototests/show.html.haml
%p
  .row
    .col-md-1
      Age:
      %span
        %strong
          = @fototest.age
    .col-md-2
      Education:
      %span
        %strong
          = @fototest.education
.table-responsive
%table.table.table-condensed.table-bordered{border: '0', summary: 'Formulario del Fototest: resultados obtenidos', width: '90%'}
  %caption.h4 Phototest - Test of the photos: Results
  %thead
    %tr.active
      %th{width: '15ex'} Category
      %th{width: '10ex'} Photos
      %th{width: '7ex'} Den
      %th{width: '7ex'} FR
      %th{width: '7ex'} AR
      %th{width: '50ex'} Verbal fluency men (VFM)
      %th{width: '50ex'} Verbal mujeres (VFW)
  %tbody
    %tr
      %td Game
      %td Cards
      %td= @fototest.cartas1
      %td= @fototest.cartas2
      %td= @fototest.cartas3
      %td{rowspan: '6'}
      %td{rowspan: '6'}
    %tr
      %td Vehicle
      %td Car
      %td= @fototest.coche1
      %td= @fototest.coche2
      %td= @fototest.coche3
    %tr
      %td Fruit
      %td Pear
      %td= @fototest.pera1
      %td= @fototest.pera2
      %td= @fototest.pera3
    %tr
      %td Musical inst.
      %td Trumpet
      %td= @fototest.trompeta1
      %td= @fototest.trompeta2
      %td= @fototest.trompeta3
    %tr
      %td Piece of clothing
      %td Shoes
      %td= @fototest.zapatos1
      %td= @fototest.zapatos2
      %td= @fototest.zapatos3
    %tr
      %td Cutlery
      %td Spoon
      %td= @fototest.cuchara1
      %td= @fototest.cuchara2
      %td= @fototest.cuchara3
    %tr
      %td{colspan: '2'} Subtotals
      %td= @fototest.deno
      %td= @fototest.rl
      %td= @fototest.rf
      %td= @fototest.total_hombres
      %td= @fototest.total_mujeres
    %tr
      %td.h4.text-right{colspan: '6'} Phototest total(Den + FR + AR + VFM + VFW)
      %td.h4= @fototest.total
- message_kind_ft = @fototest.sane? ?  "alert-success" : "alert-danger"
%p{class: "alert #{message_kind_ft} alert-dismissable lead text-center"}
  #{@fototest.diagnosis_text} with a probability of #{@fototest.probability}
%hr
.row
  .col-md-2.col-md-offset-4
    %input.btn.btn-info.btn-block{onclick: "parent.location='#{new_fototest_path}'",type: 'button', value: 'New test'}/
  .col-md-2
    %input.btn.btn-default.btn-block{onclick: 'window.print()', type: 'button', value: 'Imprimir'}/
%br